# Generated by Django 6.0.4 on 2026-04-11 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("url_lusofona", models.URLField(blank=True)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="docentes/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("sigla", models.CharField(max_length=20)),
                ("ects", models.IntegerField(default=180)),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="projetos/"),
                ),
                ("video", models.URLField(blank=True)),
                ("github", models.URLField(blank=True)),
                ("deploy", models.URLField(blank=True)),
                ("destaque", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("linguagem", "Linguagem de Programação"),
                            ("framework", "Framework"),
                            ("bd", "Base de Dados"),
                            ("devops", "DevOps / Infraestrutura"),
                            ("ferramenta", "Ferramenta"),
                            ("design", "Design / Frontend"),
                            ("outro", "Outro"),
                        ],
                        default="outro",
                        max_length=50,
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="tecnologias/"),
                ),
                ("url", models.URLField(blank=True)),
                ("nivel", models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("tipo", models.CharField(max_length=20)),
                ("nivel", models.CharField(max_length=20)),
                ("descricao", models.TextField(blank=True)),
                (
                    "projetos",
                    models.ManyToManyField(
                        blank=True, related_name="competencias", to="portfolio.projeto"
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True,
                        related_name="competencias",
                        to="portfolio.tecnologia",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="projeto",
            name="tecnologias",
            field=models.ManyToManyField(
                blank=True, related_name="projetos", to="portfolio.tecnologia"
            ),
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("tipo", models.CharField(max_length=20)),
                ("data_inicio", models.DateField(blank=True, null=True)),
                ("data_fim", models.DateField(blank=True, null=True)),
                (
                    "competencias",
                    models.ManyToManyField(
                        blank=True, related_name="formacoes", to="portfolio.competencia"
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="formacoes", to="portfolio.tecnologia"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Conquista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("tipo", models.CharField(max_length=20)),
                ("data", models.DateField(blank=True, null=True)),
                (
                    "projetos",
                    models.ManyToManyField(
                        blank=True, related_name="conquistas", to="portfolio.projeto"
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="conquistas", to="portfolio.tecnologia"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=300)),
                ("aluno", models.CharField(max_length=200)),
                ("orientador", models.CharField(blank=True, max_length=200)),
                ("ano", models.PositiveIntegerField()),
                ("interesse", models.IntegerField(default=10)),
                ("destaque", models.BooleanField(default=False)),
                (
                    "licenciatura",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tfcs",
                        to="portfolio.licenciatura",
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        blank=True, related_name="tfcs", to="portfolio.tecnologia"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("sigla", models.CharField(blank=True, max_length=20)),
                ("ano", models.IntegerField(default=4)),
                ("semestre", models.IntegerField(default=2)),
                ("obrigatoria", models.BooleanField(default=True)),
                (
                    "docentes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="unidades_curriculares",
                        to="portfolio.docente",
                    ),
                ),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unidades_curriculares",
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="projeto",
            name="unidade_curricular",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projetos",
                to="portfolio.unidadecurricular",
            ),
        ),
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("entidade_relacionada", models.CharField(max_length=50)),
                ("descricao", models.TextField()),
                ("decisoes", models.TextField(blank=True)),
                ("erros", models.TextField(blank=True)),
                ("uso_ia", models.TextField(blank=True)),
                (
                    "foto_caderno",
                    models.ImageField(blank=True, null=True, upload_to="makingof/"),
                ),
                (
                    "der",
                    models.ImageField(blank=True, null=True, upload_to="makingof/der/"),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="making_of",
                        to="portfolio.projeto",
                    ),
                ),
                (
                    "tecnologia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="making_of",
                        to="portfolio.tecnologia",
                    ),
                ),
                (
                    "unidade_curricular",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="making_of",
                        to="portfolio.unidadecurricular",
                    ),
                ),
            ],
        ),
    ]
